### ISSUE TITLE
Sparse directions

### ISSUE THREAD

**Issue by jbaker6953** [alexlance/signal-message-exporter#10]
Windows 10. Installed Docker. Created the image for signal-message-exporter. It downloaded a lot of stuff and did a lot of compiling sources. What now? When I try to run an image it just exits. I'm new to Docker and can't seem to launch the image in a way that allows me to interact with it to allow me to follow the instructions. A little help on the process of setting up the Docker container and the necessary preparations needed before we can go on with the instructions for creating the environment variables and running the Python script would be helpful.

**Comment by jbaker6953** [comment]
I was able to get a container running interactively with the image created by the Dockerfile, but this is the result:
```
# export SIG_KEY=xxxxxxxxxxxxxxxxxxxxxxxx                 
# export SIG_FILE=signal-2022-12-30-01-09-00.backup
# make run
make: *** No rule to make target 'run'.  Stop.
```

**Comment by jbaker6953** [comment]
Getting further along. I realize we're not supposed to be in the container, but rather run the command from the host console. Tried that.

```
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
docker run -e SIG_KEY -e SIG_FILE -it -v ${PWD}:/root/ workspace python3 signal-message-exporter.py
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
make: *** [Makefile:6: run] Error 125
```

**Comment by jbaker6953** [comment]
OK. Instructions for Windows:

1. Download and install Docker. Make sure to install using WSL.
2. Make sure the Docker Engine is running.
3. Download the contents of this repository using the Code -> Download ZIP link at the top of the project page.
4. Unzip the contents of this repository to a path that does not contain spaces (e.g., C:\signal-message-exporter).
5. Copy your Signal backup file to the C:\signal-message-exporter directory.
6. Open MAKEFILE in a text editor such as Notepad or Notepad++ and replace `$${PWD}` with `/c/signal-message-exporter` and save the file.
7. Open a command prompt in the C:\signal-message-exporter directory.
8. Type `set SIG_KEY=123451234512345123451234512345` using the 30-digit number of your Signal backup without spaces and press ENTER.
9. Type `set SIG_FILE=signal-2022-12-30-11-33-00.backup` using the name of your Signal backup and press ENTER.
10. Type `make run` and press ENTER.

**Comment by alexlance** [comment]
Thank you for the write-up. I've added a link to this issue in the readme, as well as a link to some windows instructions that someone posted on reddit.
