### ISSUE TITLE
Feature: Export to different formats (PDF, HTML)

### ISSUE THREAD

**Issue by Skaronator** [alexlance/signal-message-exporter#20]
This might not be the scope of this project, but it would be wonderful if the chat messages could be exported to a different format—preferable HTML and PDF.

I found this projects which already does that, but it’s using the data from the Signal Desktop App, which misses some important messages in my case. https://github.com/LiroyvH/signal-export

**Comment by alexlance** [comment]
Hey there - ok so this project exports the messages into a format that's compatible with the android app: Sms Backup and Restore. The people from that project suggest this sort of approach for viewing the messages in a web browser:

https://www.synctech.com.au/sms-backup-restore/view-or-edit-backup-files-on-computer/

**Comment by bepaald** [comment]
@Skaronator: Export to HTML is available from the original project at https://github.com/bepaald/signalbackup-tools#export ;-)

(though it is very new functionality, you may encounter issues, and I'd gladly hear about them)

**Comment by Skaronator** [comment]
@bepaald Just gave this a try with your last commit and this feature is astonishing! Wonderful job! I've one improvement suggestion, but I'll create an issue in your repository.

Closing this issue :)
