### ISSUE TITLE
Is docker actually necessary?

### ISSUE THREAD

**Issue by clampak** [alexlance/signal-message-exporter#9]
Is there a way to use this without docker?  I'm working on a Debian distro in WSL.  Docker doesn't seem to be recognized when I install it via apt, and just wondering if there could be a workaround.  I've installed all the dependencies in the Dockerfile, and built signalbackup-tools, but not sure how to proceed from there.

**Comment by alexlance** [comment]
Yes it's probably not necessary if you've installed everything in the Dockerfile.

I think you could probably just run something like this:

    export SIG_KEY=...
    export SIG_FILE=...
    python3 signal-message-exporter.py

(as long as signalbackup-tools is in /usr/bin/signalbackup-tools, as that's where the python script is looking for it on Linux systems)

**Comment by clampak** [comment]
Thanks, that worked like a charm!
